### ISSUE TITLE
Instal custom flycap SDK

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/installer#18]
From our testing on SubjuGator, running pointgrey_camera_driver compiled with a newer version of flycap sdk (2.11 vs default 2.9 installed by driver's CMake) seems to improve reliability, framerate, and other issues. I propose:

* Maintain a fork of pointgrey_camera_driver which downloads a newer version of Flycap SDK. Add this fork as a submodule of mil_common or Subjugator, or clone this fork separately in the install script. We'll have to remember to occasionally merge in from upstream (after testing it)
* Clone the latest upstream of pointgrey_camera_driver during install process, but also manually install a newer version of Flycap sdk, so when pointgrey_camera_driver compiles it uses this preinstalled version instead of downloading its own.

Thoughts?

**Comment by DSsoto** [comment]
I kind of like the idea of having our own fork of the driver. It could be nice to eventually just do our own custom setup starting from the fork.

**Comment by sentree** [comment]
From what I've seen, the new SDK seems to improve performance on the sub and not have any negative effects. I think making the driver a submodule of mil_common sounds like a good idea, but I'm skeptical about whether or not we need to maintain a fork of it. Is there anything we actually want to change with the driver? If so, why can these changes not simply be made to the upstream driver via a pull request? I propose we add the driver as a submodule and add a prompt to the install script for installing the latest version of the SDK.

**Comment by kev-the-dev** [comment]
There's actually an active discussion on pointgrey_camera_driver github about what to do about kinetic/16.04. I agree with @whispercoros. Let's make it a submodule, pointing to upstream for now (we can always point the submodule to our own fork later) and add it to the install script.

**Comment by sentree** [comment]
This should be complete once #19 and uf-mil/mil_common#80 are merged. The later will not build until the former is merged and the docker containers are rebuilt with the new install script. It is also highly recommended to run this command after both of these are merged in order to remove the old pointgrey driver package from your existing systems:

    sudo apt-get autoremove --purge ros-kinetic-pointgrey-camera-driver

**Comment by sentree** [comment]
Both of these pull requests were merged and successful builds have been observed both on CI and in the wild.
