### ISSUE TITLE
Script not sourcing on the current shell

### ISSUE THREAD

**Issue by RustyBamboo** [uf-mil/installer#7]
Problem:
- ROS setup bash is not being sourced in the current shell terminal which causes catkin to also fail.

To replicate:
- Fresh install. No ROS sourcing.
- Run script

Solution?
- I have no clue. The bash if statements look a little sketch and might be resulting in not intended result.

**Comment by sentree** [comment]
Are you suggesting that the script is not sourcing the ROS setup.sh in the shell that initiated it or in the shell that it is running in? Also, can you please point me to a line on the current master that you describe as sketch? If I recall correctly, the script will source both the ROS runcom and workspace runcom on the script's shell outside of any other logic.

**Comment by DSsoto** [comment]
@RustyBamboo was unable to reproduce
